# Generated by Django 3.2.7 on 2021-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211101_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='Документы'),
        ),
    ]
