# Generated by Django 3.2.7 on 2021-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документы'),
        ),
    ]
