# Generated by Django 3.2.7 on 2021-11-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
