# Generated by Django 3.2.7 on 2021-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ-1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ-2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ-3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover4',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ-4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью поста'),
        ),
    ]
