# Generated by Django 3.2.7 on 2021-11-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211103_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover4',
        ),
    ]
