# Generated by Django 3.2.7 on 2021-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='banner',
            name='titles',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
