# Generated by Django 3.2.7 on 2021-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_banner_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'created'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='titles',
            new_name='title',
        ),
    ]
