# Generated by Django 3.2.7 on 2021-11-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20211105_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
    ]
