# Generated by Django 3.2.7 on 2021-11-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_banner_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
